/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Compiler {
  constructor()
  /**
   * Cross-module per-file pass: inline `@inline` donors the consumer imports.
   * The JS plugin resolves + reads the donor modules and passes them here.
   */
  compileFileCross(id: string, code: string, donors: Array<DonorModule>, options?: CompileOptions | undefined | null): CompileResult
  /** Per-file pass — universal (every bundler has a `transform` hook). */
  compileFile(id: string, code: string, options?: CompileOptions | undefined | null): CompileResult
  /** Whole-program pass — rollup-family `renderChunk` only. */
  compileChunk(id: string, code: string, options?: CompileOptions | undefined | null): CompileResult
  /**
   * Run a single named pass in isolation. Returns null for an unknown
   * pass name.
   */
  runPass(name: string, id: string, code: string): CompileResult | null
}

export interface CompileOptions {
  sourcemap?: boolean
  allowLibraryInline?: boolean
}

export interface CompileResult {
  code: string
  /** JSON source map string, when source maps are enabled. */
  map?: string
  /**
   * Whether any pass actually rewrote the input. The host returns a no-op
   * when false, instead of handing back an identical reprint.
   */
  changed: boolean
  /** Per-pass counts of what the pipeline did (powers the playground panel). */
  stats: CompileStats
}

/**
 * Per-pass optimization counts — mirrors `compilecat_core::Stats`. napi maps the
 * snake_case fields to camelCase on the JS side (`removedDeadCode`, …).
 */
export interface CompileStats {
  inlined: number
  unrolled: number
  sroa: number
  folded: number
  removedDeadCode: number
  flowInlined: number
  deadAssigns: number
  minimized: number
  inlinedVariables: number
  stripped: number
}

export interface DonorModule {
  specifier: string
  /**
   * The donor's own resolved path — lets the core rebase the donor's relative
   * imports when forwarding them into the consumer, and match it as a
   * re-export target.
   */
  path: string
  code: string
  /** Resolved re-export/import edges of this donor (specifier → path). */
  resolved: Array<ResolvedEdge>
}

/**
 * Identity reprint (parse → codegen, no passes). The differential harness runs
 * both pipelines' output through this so only semantic diffs remain.
 */
export declare function format(id: string, code: string): string

/**
 * A donor module the consumer imports from (already resolved + read by the JS
 * plugin, which owns module resolution and the filesystem/watch).
 * A resolved `… from '<specifier>'` edge of a donor — lets the core follow a
 * re-export (`export * as vec3 from './vec3'`) to the module at `path`.
 */
export interface ResolvedEdge {
  specifier: string
  path: string
}
