/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Compiler {
  constructor()
  /**
   * Cross-module per-file pass: inline `@inline` dependencies the consumer imports.
   * The JS plugin resolves + reads the dependency modules and passes them here.
   */
  compileFileCross(id: string, code: string, dependencies: Array<Dependency>, options?: CompileOptions | undefined | null): CompileResult
  /** Per-file pass — universal (every bundler has a `transform` hook). */
  compileFile(id: string, code: string, options?: CompileOptions | undefined | null): CompileResult
  /** Whole-program pass — rollup-family `renderChunk` only. */
  compileChunk(id: string, code: string, options?: CompileOptions | undefined | null): CompileResult
  /**
   * Run a single named pass in isolation. Returns null for an unknown
   * pass name.
   */
  runPass(name: string, id: string, code: string): CompileResult | null
}

export interface CompileOptions {
  sourcemap?: boolean
  allowLibraryInline?: boolean
}

export interface CompileResult {
  code: string
  /** JSON source map string, when source maps are enabled. */
  map?: string
  /**
   * Whether any pass actually rewrote the input. The host returns a no-op
   * when false, instead of handing back an identical reprint.
   */
  changed: boolean
  /** Per-pass counts of what the pipeline did (powers the playground panel). */
  stats: CompileStats
}

/**
 * Per-pass optimization counts — mirrors `compilecat_core::Stats`. napi maps the
 * snake_case fields to camelCase on the JS side (`removedDeadCode`, …).
 */
export interface CompileStats {
  inlined: number
  unrolled: number
  sroa: number
  folded: number
  removedDeadCode: number
  flowInlined: number
  deadAssigns: number
  minimized: number
  inlinedVariables: number
  stripped: number
}

export interface Dependency {
  specifier: string
  /**
   * The dependency's own resolved path — lets the core rebase the dependency's relative
   * imports when forwarding them into the consumer, and match it as a
   * re-export target.
   */
  path: string
  code: string
  /** Resolved re-export/import edges of this dependency (specifier → path). */
  resolved: Array<ResolvedEdge>
}

/**
 * The specifiers the dependency BFS should follow from ONE module — the AST-based
 * replacement for the plugin's brittle dependency-edge regexes. `id` is the dependency's
 * path, used only to pick the source type (so `.d.ts`/`.tsx`/`.js` parse
 * correctly); the return is a dedup'd, order-stable list of import/re-export
 * specifiers `S` the plugin should read as further dependencies (see
 * [`compilecat_core::dependency_edges`]).
 */
export declare function dependencyEdges(id: string, code: string): Array<string>

/**
 * Identity reprint (parse → codegen, no passes). The differential harness runs
 * both pipelines' output through this so only semantic diffs remain.
 */
export declare function format(id: string, code: string): string

/**
 * One module edge the host still needs but that isn't reachable within the
 * dependencies gathered so far — the demand-driven counterpart to a `Dependency`.
 * The plugin resolves `specifier` relative to `from_path` (as a runtime module for
 * `kind: "value"`, a type module for `kind: "type"`), reads it, adds it as a dependency,
 * and calls [`resolution_frontier`] again until the frontier is empty.
 */
export interface FrontierRequest {
  specifier: string
  fromPath: string
  /** `"value"` (runtime `.js`) or `"type"` (`.d.ts`). */
  kind: string
}

/**
 * The module edges the host still needs given the dependencies gathered so far — the
 * demand-driven dependency-gather fixpoint's "what's still missing?" query. STATELESS:
 * the plugin calls this with a growing `provided` set until it returns `[]`, then
 * hands the assembled set to `compileFileCross` (the unchanged inliner). A
 * directive-less host needs nothing → `[]`, UNLESS it calls a first-party
 * `@inline`-def name in `inline_def_names` (the build-start index of
 * `/* @inline *\/ export function NAME` defs) — then that def's module is a value
 * need. `id` is the host's path (picks the source type). See
 * [`compilecat_core::resolution_frontier`].
 */
export declare function resolutionFrontier(id: string, code: string, provided: Array<Dependency>, inlineDefNames: Array<string>): Array<FrontierRequest>

/**
 * A dependency module the consumer imports from (already resolved + read by the JS
 * plugin, which owns module resolution and the filesystem/watch).
 * A resolved `… from '<specifier>'` edge of a dependency — lets the core follow a
 * re-export (`export * as vec3 from './vec3'`) to the module at `path`.
 */
export interface ResolvedEdge {
  specifier: string
  path: string
}
